// See https://aka.ms/new-console-template for more information
int A = 440;
int B = 494;
int C = 262;
int D = 294;
int E = 330;
int F = 349;
int G = 392;
int wholeNote = 1600;
int half = wholeNote/2;
int quarter = half/2;
int eighth = quarter/2;
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkYellow;
Console.Clear();
Console.Beep(F,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkRed;
Console.Clear();
Console.Beep(G,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkRed;
Console.Clear();
Console.Beep(G,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkYellow;
Console.Clear();
Console.Beep(F,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);/*Not a Whole Note*/
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkYellow;
Console.Clear();
Console.Beep(F,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkRed;
Console.Clear();
Console.Beep(G,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkRed;
Console.Clear();
Console.Beep(G,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkYellow;
Console.Clear();
Console.Beep(F,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);/*not a Whole Note*/
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkYellow;
Console.Clear();
Console.Beep(F,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkYellow;
Console.Clear();
Console.Beep(F,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkYellow;
Console.Clear();
Console.Beep(F,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkRed;
Console.Clear();
Console.Beep(G,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkRed;
Console.Clear();
Console.Beep(G,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkYellow;
Console.Clear();
Console.Beep(F,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkYellow;
Console.Clear();
Console.Beep(F,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkBlue;
Console.Clear();
Console.Beep(E,wholeNote);
Console.BackgroundColor= ConsoleColor.DarkGreen;
Console.Clear();
Console.Beep(D,wholeNote);/*not Whole Note*/
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);
Console.BackgroundColor= ConsoleColor.Cyan;
Console.Clear();
Console.Beep(C,wholeNote);/*not A Whole note*/

